### ISSUE TITLE
[User Story] As a Customer, I want to analyze the reviews of a Business So that I know if it's legit or not

### ISSUE THREAD

**Issue by SethCKL** [cs3203-team1/goodmeh-frontend#11]
What does the reviews of a Business truly mean? 

As a Customer I want to know how many are fake, how many are high impact, how many have pictures attached.

"Can the reviews be trusted?"

So that I can make a better decision to try out a Business or not

**Comment by zhekaiii** [comment]
Score Component (just numbers) something like this
![Image](https://github.com/user-attachments/assets/f57325e5-3473-4b1a-8bb9-d1cb3c68b4e5)
We display the original vs processed
